# Generated by Django 4.1.6 on 2023-04-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_course_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseenroll',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='courseenroll',
            old_name='student_id',
            new_name='student',
        ),
    ]
