# Generated by Django 4.1.6 on 2023-04-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_courseenroll_course_alter_courseenroll_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenroll',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
