# Generated by Django 4.1.6 on 2023-04-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_courseenroll_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='email',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
